// <auto-generated />
namespace Group_5_Hospital_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _jasonmodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_jasonmodels));
        
        string IMigrationMetadata.Id
        {
            get { return "202004011933273__jasonmodels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
