// <auto-generated />
namespace Group_5_Hospital_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class donor1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(donor1));
        
        string IMigrationMetadata.Id
        {
            get { return "202004010000296_donor1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
